#%RAML 1.0
title: Library Management API
version: v1
baseUri: http://localhost:3000/api
mediaType:  application/json

types:
  Book:
    type: object
    properties:
      id: string
      title: string
      authorId: string
  BookInput:
    type: object
    properties:
      title: string
      authorId: string

/books:
  get:
    description: Get all books
    responses:
      200:
        body:
          application/json:
            type: Book[]
  post:
    description: Add a new book
    body:
      application/json:
        type: BookInput
    responses:
      201:
        description: Created
